import { readdirSync, readFileSync } from "fs";
import { join, relative, resolve, basename, extname } from "path";
import matter from "gray-matter";
import { atomicWriteText } from "./vault_fs";

type IndexSection =
  | "Start Here"
  | "Entities"
  | "Concepts"
  | "Topics"
  | "Research"
  | "Sessions"
  | "Skills"
  | "Source Summaries"
  | "Dreams"
  | "Other";

function isoDate(date = new Date()): string {
  return date.toISOString().slice(0, 10);
}

function walkMdFiles(root: string): string[] {
  const out: string[] = [];
  const stack: string[] = [root];
  while (stack.length) {
    const dir = stack.pop()!;
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const e of entries) {
      const full = join(dir, e.name);
      if (e.isDirectory()) {
        if (e.name.startsWith(".")) continue;
        stack.push(full);
      } else if (e.isFile() && e.name.endsWith(".md")) {
        out.push(full);
      }
    }
  }
  return out;
}

function sectionFromRelPath(rel: string): IndexSection {
  const norm = rel.replace(/\\/g, "/");
  const parts = norm.split("/");
  const bucket = parts[1] ?? "";
  const fileBase = basename(norm, extname(norm)).toLowerCase();
  if (fileBase === "start") return "Start Here";
  switch (bucket) {
    case "entities": return "Entities";
    case "concepts": return "Concepts";
    case "topics": return "Topics";
    case "research": return "Research";
    case "sessions": return "Sessions";
    case "skills": return "Skills";
    case "sources": return "Source Summaries";
    case "dreams": return "Dreams";
    default: return "Other";
  }
}

function firstH1(body: string): string | null {
  const m = body.match(/^\s*#\s+(.+?)\s*$/m);
  return m?.[1]?.trim() ?? null;
}

export async function rebuildWikiIndex(vaultPath: string, now = new Date()): Promise<void> {
  const wikiRoot = join(vaultPath, "wiki");
  const indexPath = join(wikiRoot, "index.md");

  const files = walkMdFiles(wikiRoot)
    .filter(p => !p.endsWith(`${join("wiki", "index.md")}`))
    .filter(p => basename(p).toLowerCase() !== "index.md"); // exclude itself

  const sections = new Map<IndexSection, Array<{ fileBase: string; title: string; sources: number; rel: string }>>();
  for (const f of files) {
    const rel = relative(vaultPath, f);
    const sec = sectionFromRelPath(rel);

    let raw = "";
    try {
      raw = readFileSync(f, "utf-8");
    } catch {
      continue;
    }

    const parsed = matter(raw);
    const fileBase = basename(f, extname(f));
    const title = String(parsed.data?.title ?? firstH1(parsed.content ?? "") ?? fileBase);
    const sources = typeof parsed.data?.sources === "number" ? parsed.data.sources : Number.parseInt(String(parsed.data?.sources ?? 0), 10) || 0;

    if (!sections.has(sec)) sections.set(sec, []);
    sections.get(sec)!.push({ fileBase, title, sources, rel });
  }

  // Stable ordering
  for (const list of sections.values()) {
    list.sort((a, b) => a.title.localeCompare(b.title));
  }

  const fm = [
    "---",
    "title: Wiki Index",
    "type: index",
    "role: operational",
    "retrieval_priority: low",
    "tags: [navigation, index, operational]",
    "sources: 0",
    `created: ${isoDate(now)}`,
    `updated: ${isoDate(now)}`,
    "---",
    "",
  ].join("\n");

  const renderSection = (name: IndexSection) => {
    const items = sections.get(name) ?? [];
    const lines: string[] = [];
    lines.push(`## ${name}`, "");
    if (items.length === 0) {
      lines.push("- *(none)*", "");
      return lines.join("\n");
    }
    for (const it of items) {
      const src = it.sources > 0 ? ` (${it.sources} sources)` : "";
      lines.push(`- [[${it.fileBase}]] — ${it.title}${src}`);
    }
    lines.push("");
    return lines.join("\n");
  };

  const body = [
    "# Wiki Index",
    "",
    "Central catalog of all wiki pages. This file is generated by the daemon to prevent index rot.",
    "",
    renderSection("Start Here"),
    renderSection("Entities"),
    renderSection("Concepts"),
    renderSection("Topics"),
    renderSection("Research"),
    renderSection("Sessions"),
    renderSection("Skills"),
    renderSection("Dreams"),
    renderSection("Source Summaries"),
    renderSection("Other"),
  ].join("\n");

  await atomicWriteText(vaultPath, indexPath, fm + body);
}

