import { join } from "path";
import { safeWriteText } from "./vault_fs";

export async function writeOpsOutputsIndex(params: {
  vaultPath: string;
}): Promise<string> {
  const now = new Date().toISOString();
  const rel = "wiki/entities/GZMO-Ops-Outputs.md";
  const abs = join(params.vaultPath, rel);

  const outputs = [
    { path: "GZMO/health.md", why: "Human-readable health snapshot (updated periodically)." },
    { path: "GZMO/TELEMETRY.json", why: "Compact machine-readable ops telemetry (updated periodically)." },
    { path: "GZMO/embeddings.json", why: "Embedding store for vault semantic search." },
    { path: "GZMO/CHAOS_STATE.json", why: "Pulse/chaos state snapshot." },
    { path: "GZMO/Live_Stream.md", why: "Operator-facing live stream log." },
    { path: "GZMO/.gzmo_wiki_digest.json", why: "Wiki engine digest (processed cabinet entries/pages)." },
    { path: "GZMO/.gzmo_dreams_digested.json", why: "Dream engine digest (already-digested tasks)." },
    { path: "GZMO/.gzmo_auto_tasks.json", why: "Auto-task digest (stable id + rate limiting)." },
    { path: "GZMO/.gzmo_ingest_digest.json", why: "Ingest engine digest (processed raw sources)." },
  ];

  const telemetryFields = [
    "generatedAt",
    "runtime.profile / runtime.ollamaUrl / runtime.model",
    "runtime.inference.temperature|maxTokens|valence",
    "state.alive|phase|tension|energy|tick|deaths",
    "workload.inbox.pending|processing|completed|failed",
    "workload.cabinetNotes|quarantineNotes",
    "scheduler.*Enabled",
    "operatorHints[]",
  ];

  const md = [
    "---",
    "title: GZMO Ops Outputs",
    "type: entity",
    "role: canonical",
    "tags: [operations, telemetry, outputs, system]",
    "sources: 0",
    `created: "${now.slice(0, 10)}"`,
    `updated: "${now.slice(0, 10)}"`,
    "---",
    "",
    "# GZMO Ops Outputs",
    "",
    "This page is generated by the daemon as a deterministic index of operational outputs (files it writes).",
    "",
    "## Files written",
    "",
    ...outputs.map((o) => `- \`${o.path}\` — ${o.why}`),
    "",
    "## TELEMETRY.json schema (high level)",
    "",
    ...telemetryFields.map((f) => `- \`${f}\``),
    "",
    "## Notes",
    "",
    "- Prefer deterministic ops artifacts (`health.md`, `TELEMETRY.json`) over semantic search when answering operational questions.",
    "",
  ].join("\n");

  await safeWriteText(params.vaultPath, abs, md);
  return rel;
}

